name: flutter_js
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  pocketbase: ^0.7.3
  flutter_modular: any
  flutter_bloc: ^8.0.0
  bloc: ^8.0.0
  tpl_docx:
    path: pack/tpl_for_docx
  pdf: ^3.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
        # - asset: fonts/Inter-Regular.ttf
        #   weight: 400
        # - asset: fonts/Inter-Medium.ttf
        #   weight: 500
        # - asset: fonts/Inter-Bold.ttf
        #   weight: 700
  assets:
    - assets/configs/
    # - assets/templates/
    - assets/templates/JPR/
    - assets/fonts/
